var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "j",
            "sun": "Dim",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Jeu",
            "fri": "Ven",
            "sat": "Sam",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Aou",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "Pas encore implémenté",
        "to_date_view": "Cliquez pour voir la date courrante.",
        "i_undefined": "Indéfini",
        "allday_event": "Evénement sur la journée",
        "repeat_event": "Evénement répété",
        "time": "Date",
        "event": "Evenement",
        "location": "Lieu",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "Nouvel Evenement",
        "confirm_delete_event": "Voulez-vous supprimer cet événement ? ",
        "confrim_delete_event_or_all": "Voulez-vous supprimer tout les événements ou seulement celui çi ? \r\nCliquez sur [OK] pour supprimer seulement cet évenement, cliquez sur [Cancel] pour tout supprimer",
        "data_format_error": "Erreur de format de données! ",
        "invalid_title": "Le titre de l'événement ne peut être vide ou contenir ($<>)",
        "view_no_ready": "La vue n'est pas prête",
        "example": "ex : Rdv en salle 107",
        "content": "Quoi",
        "create_event": "Créer événement",
        "update_detail": "Editer les détails",
        "click_to_detail": "View details",
        "i_delete": "Supprimer",
        "day_plural": "jours",
        "others": "Autres",
        "item": ""
    }
});
